apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  ## user for build local and than push
  local:
    push: true
    useDockerCLI: true
  googleCloudBuild:
    projectId: exalted-cogency-294518
  artifacts:
    - image: adribusse/t_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: adribusse/t_client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
